<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="chassis">
        
        <link name="base_link"/>

        <link name="chassis">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
                </geometry>
                <material name="base_material">
                    <color rgba="0.8 0.0 0.1 1.0"/>
                </material>
            </visual>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${chassisMass}"/>
                <xacro:box_inertia 
                    m="${chassisMass}"
                    x="${chassisLength}"
                    y="${chassisWidth}"
                    z="${chassisHeight}"
                />
            </inertial>
        </link>

        <!-- Fixed joint to add dummy inertia link -->
        <joint name="chassis_joinz" type="fixed">
            <parent link="base_link"/>
            <child link="chassis"/>
            <origin xyz="0 0 ${wheelRadius - wheelHeight + chassisHeight/2.0}" rpy="0 0 0"/>
        </joint>

    </xacro:macro>

</robot>