<?xml version="1.0"?>
<robot name="arc" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find ars_description)/urdf/arc_utils.urdf.xacro" />
    <xacro:include filename="$(find ars_description)/urdf/arc_lidar.gazebo.xacro"/>
    <xacro:include filename="$(find ars_description)/urdf/arc_imu.gazebo.xacro"/>
    <xacro:property name="PI" value="3.1415926535897931"/>

    <!--    Model macros    -->
    <!-- Front Wheel -->
    <xacro:macro name="front_wheel" params="prefix X Y friction_coeff:=0.7 transmission_reduction:=1" >
        <joint name="${prefix}_FRONT_WHEEL_JOINT" type="continuous">
            <parent link="${prefix}_HINGE"/>
            <child link="${prefix}_FRONT_WHEEL"/>
            <origin xyz="0 0 ${Y}" rpy="0 0 0" />
            <axis xyz="0 0 1" rpy="0 0 0" />
            <dynamics damping="0.0" friction="0.0"/>
            <limit effort="100" velocity="200"/>
            <joint_properties damping="0.2" friction="0.2"/>
        </joint>

        <link name="${prefix}_FRONT_WHEEL">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
                </geometry>
            </visual>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${wheelMass}"/>
                <xacro:cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
            </inertial>
        </link>

        <gazebo reference="${prefix}_FRONT_WHEEL">
            <mu1 value="${friction_coeff}"/>
            <mu2 value="${friction_coeff}"/>
            <fdir1 value="1 0 0"/>
            <kp>10000000.0</kp>
            <kd>1.0</kd>
            <minDepth>0.005</minDepth>
            <maxVel>100.0</maxVel>
            <material>Gazebo/DarkGrey</material>
        </gazebo>

        <transmission name="${prefix}_FRONT_WHEEL_TRANS" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_FRONT_WHEEL_JOINT">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_FRONT_ACTUATOR">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>${transmission_reduction}</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <!-- Front Hinge -->
    <xacro:macro name="hinge" params="prefix X Y">
        <joint name="${prefix}_HINGE_JOINT" type="revolute">
            <parent link="${base_link_name}"/>
            <child link="${prefix}_HINGE"/>
            <origin xyz="${X} ${Y} ${wheelHeight - chassisHeight/2.0}" rpy="-${0.5*PI} 0.0 0.0"/>
            <axis xyz="0 -1 0" rpy="0 0 0"/>
            <dynamics damping="0.0" friction="0.0"/>
            <limit lower="-0.53" upper="0.53" effort="100" velocity="1"/>
        </joint>

        <link name="${prefix}_HINGE">
            <!--
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <cylinder radius="${hingeRadius}" length="${hingeLength}"/>
            </collision>
            -->
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${hingeRadius}" length="${hingeLength}"/>
                </geometry>
            </visual>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="${hingeMass}"/>
                <xacro:cylinder_inertia m="${hingeMass}" r="${hingeRadius}" h="${hingeLength}"/>
            </inertial>
        </link>

        <gazebo reference="${prefix}_WHEEL_HINGE">
            <mu1 value="0.0"/>
            <mu2 value="0.0"/>
            <kp>10000000.0</kp>
            <kd>1.0</kd>
            <fdir1 value="0 1 0"/>
            <material>Gazebo/DarkGrey</material>
        </gazebo>

        <transmission name="${prefix}_HINGE_TRANS">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_HINGE_JOINT">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_ACTUATOR">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <!-- Rear Wheel -->
    <xacro:macro name="rear_wheel" params="prefix X Y friction_coeff:=0.7 transmission_reduction:=1" >
        <joint name="${prefix}_REAR_WHEEL_JOINT" type="continuous">
            <parent link="${base_link_name}"/>
            <child link="${prefix}_REAR_WHEEL"/>
            <origin xyz="${X} ${Y} ${wheelHeight - chassisHeight/2.0}" rpy="${PI/2} 0 0" />
            <axis xyz="0 0 -1" rpy="0 0 0" />
            <dynamics damping="0.0" friction="0.0"/>
            <limit effort="100" velocity="200"/>
            <joint_properties damping="0.2" friction="0.2"/>
        </joint>

        <link name="${prefix}_REAR_WHEEL">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
                </geometry>
            </visual>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${wheelMass}"/>
                <xacro:cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
            </inertial>
        </link>

        <gazebo reference="${prefix}_REAR_WHEEL">
            <mu1 value="${friction_coeff}"/>
            <mu2 value="${friction_coeff}"/>
            <fdir1 value="1 0 0"/>
            <kp>10000000.0</kp>
            <kd>1.0</kd>
            <minDepth>0.005</minDepth>
            <maxVel>100.0</maxVel>
            <material>Gazebo/DarkGrey</material>
        </gazebo>

        <transmission name="${prefix}_REAR_WHEEL_TRANS" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_REAR_WHEEL_JOINT">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_REAR_ACTUATOR">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>${transmission_reduction}</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <!-- Chassis -->
    <xacro:macro name="chassis">

        <link name="${base_link_name}">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
                </geometry>
                <material name="base_material">
                    <color rgba="0.8 0.0 0.1 1.0"/>
                </material>
            </visual>
        </link>

        <gazebo reference="${base_link_name}">
            <material>Gazebo/Red</material>
        </gazebo>

        <!-- Fixed joint to add dummy inertia link -->
        <joint name="base_to_base_inertia" type="fixed">
            <parent link="${base_link_name}"/>
            <child link="base_inertia"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </joint>

        <!-- Dummy inertia link, because KDL cannot have inertia on the base link -->
        <link name="base_inertia">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${chassisMass}"/>
                <xacro:box_inertia m="${chassisMass}"
                            x="${chassisLength}"
                            y="${chassisWidth}"
                            z="${chassisHeight}"/>
            </inertial>
        </link>

    </xacro:macro>
    
    <xacro:macro name="arc">
        <xacro:chassis/>
        
        <xacro:hinge prefix="LEFT" 
            X = "${hingeX}"
            Y = "${chassisWidth/2+hingeLength/2}"/>

        <xacro:hinge prefix="RIGHT" 
            X = "${hingeX}"
            Y = "${-chassisWidth/2-hingeLength/2}"/>

        <xacro:front_wheel prefix="LEFT" 
            X="0"
            Y="${hingeLength/2+wheelWidth/2}"
            friction_coeff="0.5" />

        <xacro:front_wheel prefix="RIGHT" 
            X="0"
            Y="${-hingeLength/2-wheelWidth/2}"
            friction_coeff="0.5"/>
        
        <xacro:rear_wheel prefix="LEFT"
            X="${backWheelX}"
            Y="${chassisWidth/2+wheelClearance+wheelWidth/2}"
            friction_coeff="0.0" />

        <xacro:rear_wheel prefix="RIGHT" 
            X="${backWheelX}"
            Y="${-chassisWidth/2-wheelClearance-wheelWidth/2}"
            friction_coeff="0.0" />
        
        <xacro:IMU base_link="${base_link_name}"/>
        <xacro:LIDAR base_link="${base_link_name}"/>
        
    </xacro:macro>
</robot>
